### ISSUE TITLE
Edit Calendar View + Airtable: Add change tracking for when Challenges are edited

### ISSUE THREAD

**Issue by arapawa** [dannytpeck/calendar-builder-client#5]
Like Comment icon, but for Edit icon

- [ ] Column in airtable for Changed
- [ ] Make 'edited' icon
- [ ] Track edits for Title, Short Description, and Long Description

**Comment by arapawa** [comment]
@dannytpeck Added the icon as part of e55e9d28c7d710f3d007815af55563191ab9578b
The icon is in the images folder as icon_edit_notification.svg.
